INSERT ALL
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(1, 'Duke','Savage')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(2, 'Libby','Berufort')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(3, 'Isadora','Williamson')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(4, 'Dickie','Woods')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(5, 'Bill','Brook')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(6, 'Abram','Denzel')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(7, 'Georgie','Barkworth')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(8, 'Ringo','Walton')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(9, 'Margaret','Wise')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(10,'Jesus','Tudor')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(11,'Henriette','Moloney')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(12,'Christy','Allport')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(13,'Fip','Massey')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(14,'Marion','Joule')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(15,'Jeff','Harley')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(16,'Linda','Reuther')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(17,'Angeline','Dodd')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(18,'Dick','Cook')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(19,'Penny','McCarthy')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(20,'Star','Brawn')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(21,'Duane','Greenawa')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(22,'Julie','Fordham')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(23,'Charleen','Bohun')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(24,'Ariel','Ayling')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(25,'Kitto','Higgins')
INTO t_celebrity (celebrity_id,first_name,last_name) VALUES(26,'Sybel','Wyeth')
SELECT * FROM DUAL
