INSERT ALL
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient', 'authorization_code')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient', 'password')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient', 'client_credentials')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient', 'refresh_token')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient', 'implicit')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientReadOnly', 'authorization_code')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientReadOnly', 'password')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientReadOnly', 'client_credentials')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientReadOnly', 'refresh_token')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientReadOnly', 'implicit')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientIllegalUri', 'authorization_code')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClientIllegalResource', 'authorization_code')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient2', 'authorization_code')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient2', 'password')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient2', 'client_credentials')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient2', 'refresh_token')
INTO authorized_grant_types(client_id, authorized_grant_type) VALUES('testClient2', 'implicit')
SELECT * FROM DUAL
