INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(1,'Spring Test Server 1','Spring OS 64bit','Spring Core i9-440','DDR3-1600 16GB','Spring Chip','Spring SSD 500GB','Spring Power 800W',100000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(2,'Spring Test Server 2','Spring OS 64bit','Spring Core i9-441','DDR3-1600 8GB','Spring Chip','Spring SSD 200GB','Spring Power 600W',80000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(3,'Spring Test Server 3','Spring OS 64bit','Spring Core i9-442','DDR3-1600 16GB','Spring Chip','Spring SSD 500GB','Spring Power 800W',130000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(4,'Spring Test Server 4','Spring OS 64bit','Spring Core i9-443','DDR3-1600 8GB','Spring Chip','Spring SSD 200GB','Spring Power 600W',100000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(5,'Spring Test Server 5','Spring OS 64bit','Spring Core i9-444','DDR3-1600 16GB','Spring Chip','Spring SSD 1TB','Spring Power 800W',180000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(6,'Local Test Server 1','Local OS 64bit','Local Core i3-440','DDR3-1600 16GB','Local Chip','Local SSD 500GB','Local Power 800W',50000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(7,'Local Test Server 2','Local OS 64bit','Local Core i3-441','DDR3-1600 8GB','Local Chip','Local SSD 200GB','Local Power 600W',50000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(8,'Local Test Server 3','Local OS 64bit','Local Core i3-442','DDR3-1600 16GB','Local Chip','Local SSD 500GB','Local Power 800W',70000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(9,'Local Test Server 4','Local OS 64bit','Local Core i3-443','DDR3-1600 8GB','Local Chip','Local SSD 200GB','Local Power 600W',70000);
INSERT INTO t_personal_computer (personal_computer_id,personal_computer_name,os,cpu,ram,videocard,hdd,power,price) VALUES(10,'Local Test Server 5','Local OS 64bit','Local Core i3-444','DDR3-1600 16GB','Local Chip','Local SSD 1TB','Local Power 800W',100000);

commit;
