INSERT INTO
    t_celebrity (celebrity_id,first_name,last_name)
VALUES
    (1, 'Duke','Savage'),
    (2, 'Libby','Berufort'),
    (3, 'Isadora','Williamson'),
    (4, 'Dickie','Woods'),
    (5, 'Bill','Brook'),
    (6, 'Abram','Denzel'),
    (7, 'Georgie','Barkworth'),
    (8, 'Ringo','Walton'),
    (9, 'Margaret','Wise'),
    (10,'Jesus','Tudor'),
    (11,'Henriette','Moloney'),
    (12,'Christy','Allport'),
    (13,'Fip','Massey'),
    (14,'Marion','Joule'),
    (15,'Jeff','Harley'),
    (16,'Linda','Reuther'),
    (17,'Angeline','Dodd'),
    (18,'Dick','Cook'),
    (19,'Penny','McCarthy'),
    (20,'Star','Brawn'),
    (21,'Duane','Greenawa'),
    (22,'Julie','Fordham'),
    (23,'Charleen','Bohun'),
    (24,'Ariel','Ayling'),
    (25,'Kitto','Higgins'),
    (26,'Sybel','Wyeth')
