/*
 * Copyright(c) 2014-2017 NTT Corporation.
 */
package jp.co.ntt.fw.spring.functionaltest.ws.soap.wsimport;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 */
@WebFault(name = "WebFault", targetNamespace = "http://functionaltest.spring.fw.ntt.co.jp/todo")
public class WebFaultException extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private WebFaultBean faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public WebFaultException(String message, WebFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WebFaultException(String message, WebFaultBean faultInfo,
            Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: jp.co.ntt.fw.spring.functionaltest.ws.soap.wsimport.WebFaultBean
     */
    public WebFaultBean getFaultInfo() {
        return faultInfo;
    }

}
